### ISSUE TITLE
[Bug]: 履歴項目の More Vert アイコンで開く BottomSheet 内で InkWell のホバーエフェクトが効かない

### ISSUE THREAD

**Issue by keigomichi** [Dev-roll/qrio#83]
### 不具合の内容

履歴項目の More Vert アイコンで開く BottomSheet 内で InkWell のホバーエフェクトが効かない

### 動作環境

Android

**Comment by notchcoder** [comment]
### わかっていること

- BottomSheetに背景色をつけると、InkWellのリップルエフェクトが表示されない
